# Generated by Django 2.0.4 on 2018-05-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='noticie',
            new_name='News',
        ),
    ]
