# Generated by Django 2.0.4 on 2018-05-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_news_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='theme',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
