# Generated by Django 2.0.4 on 2018-05-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180529_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nome',
        ),
    ]
