# Generated by Django 2.0.4 on 2018-05-31 13:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(upload_to=core.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='resume',
            field=models.CharField(max_length=100, null=True, verbose_name='Resumo'),
        ),
    ]
