# Generated by Django 2.0.4 on 2018-05-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180531_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='resume',
            field=models.CharField(max_length=50, null=True, verbose_name='Resumo'),
        ),
    ]
