# Generated by Django 2.0.4 on 2018-05-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180531_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Titulo'),
        ),
    ]
